/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "vm-agent.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Request, Request, AUTO)


PB_BIND(Request_Quit, Request_Quit, AUTO)


PB_BIND(Request_RunProcess, Request_RunProcess, AUTO)


PB_BIND(Request_KillProcess, Request_KillProcess, AUTO)


PB_BIND(Request_Mount9P, Request_Mount9P, AUTO)


PB_BIND(Request_QueryOutput, Request_QueryOutput, AUTO)


PB_BIND(Request_PutInput, Request_PutInput, AUTO)


PB_BIND(Request_UploadFile, Request_UploadFile, AUTO)


PB_BIND(RedirectFd, RedirectFd, AUTO)



