/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_VM_AGENT_PB_H_INCLUDED
#define PB_VM_AGENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Request_Mount9P {
    pb_callback_t vol_tag;
    pb_callback_t path;
} Request_Mount9P;

typedef struct _Request_Quit {
    char dummy_field;
} Request_Quit;

typedef struct _RedirectFd {
    uint32_t fd;
    pb_size_t which_Type;
    union {
        pb_callback_t output_file;
        uint32_t pipe_blocking;
        uint32_t pipe_cyclic;
        uint32_t input_pipe_blocking;
    } Type;
} RedirectFd;

typedef struct _Request_KillProcess {
    uint64_t process_id;
} Request_KillProcess;

typedef struct _Request_PutInput {
    uint64_t process_id;
    uint32_t fd;
    pb_callback_t data;
} Request_PutInput;

typedef struct _Request_QueryOutput {
    uint64_t process_id;
    bool has_offset;
    uint64_t offset;
    bool has_len;
    uint64_t len;
} Request_QueryOutput;

typedef struct _Request_RunProcess {
    pb_callback_t bin;
    pb_callback_t arg;
    pb_callback_t env;
    bool has_uid;
    uint32_t uid;
    bool has_gid;
    uint32_t gid;
    pb_callback_t redirect_fd;
} Request_RunProcess;

typedef struct _Request_UploadFile {
    pb_callback_t file_path;
    bool has_file_erm;
    uint32_t file_erm;
    bool has_uid;
    uint32_t uid;
    bool has_guid;
    uint32_t guid;
    pb_callback_t data;
} Request_UploadFile;

typedef struct _Request {
    uint32_t id;
    pb_size_t which_Command;
    union {
        Request_Quit quit;
        Request_RunProcess run;
        Request_KillProcess kill;
        Request_Mount9P mount_9p;
        Request_QueryOutput query_output;
        Request_PutInput put_input;
        Request_UploadFile upload_file;
    } Command;
} Request;


/* Initializer values for message structs */
#define Request_init_default                     {0, 0, {Request_Quit_init_default}}
#define Request_Quit_init_default                {0}
#define Request_RunProcess_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}}
#define Request_KillProcess_init_default         {0}
#define Request_Mount9P_init_default             {{{NULL}, NULL}, {{NULL}, NULL}}
#define Request_QueryOutput_init_default         {0, false, 0, false, 0}
#define Request_PutInput_init_default            {0, 0, {{NULL}, NULL}}
#define Request_UploadFile_init_default          {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define RedirectFd_init_default                  {0, 0, {{{NULL}, NULL}}}
#define Request_init_zero                        {0, 0, {Request_Quit_init_zero}}
#define Request_Quit_init_zero                   {0}
#define Request_RunProcess_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}}
#define Request_KillProcess_init_zero            {0}
#define Request_Mount9P_init_zero                {{{NULL}, NULL}, {{NULL}, NULL}}
#define Request_QueryOutput_init_zero            {0, false, 0, false, 0}
#define Request_PutInput_init_zero               {0, 0, {{NULL}, NULL}}
#define Request_UploadFile_init_zero             {{{NULL}, NULL}, false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define RedirectFd_init_zero                     {0, 0, {{{NULL}, NULL}}}

/* Field tags (for use in manual encoding/decoding) */
#define Request_Mount9P_vol_tag_tag              1
#define Request_Mount9P_path_tag                 2
#define RedirectFd_output_file_tag               2
#define RedirectFd_pipe_blocking_tag             3
#define RedirectFd_pipe_cyclic_tag               4
#define RedirectFd_input_pipe_blocking_tag       5
#define RedirectFd_fd_tag                        1
#define Request_KillProcess_process_id_tag       1
#define Request_PutInput_process_id_tag          1
#define Request_PutInput_fd_tag                  2
#define Request_PutInput_data_tag                3
#define Request_QueryOutput_process_id_tag       1
#define Request_QueryOutput_offset_tag           2
#define Request_QueryOutput_len_tag              3
#define Request_RunProcess_bin_tag               1
#define Request_RunProcess_arg_tag               2
#define Request_RunProcess_env_tag               3
#define Request_RunProcess_uid_tag               4
#define Request_RunProcess_gid_tag               5
#define Request_RunProcess_redirect_fd_tag       6
#define Request_UploadFile_file_path_tag         1
#define Request_UploadFile_file_erm_tag          2
#define Request_UploadFile_uid_tag               3
#define Request_UploadFile_guid_tag              4
#define Request_UploadFile_data_tag              5
#define Request_quit_tag                         2
#define Request_run_tag                          3
#define Request_kill_tag                         4
#define Request_mount_9p_tag                     5
#define Request_query_output_tag                 6
#define Request_put_input_tag                    7
#define Request_upload_file_tag                  8
#define Request_id_tag                           1

/* Struct field encoding specification for nanopb */
#define Request_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,quit,Command.quit),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,run,Command.run),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,kill,Command.kill),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,mount_9p,Command.mount_9p),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,query_output,Command.query_output),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,put_input,Command.put_input),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (Command,upload_file,Command.upload_file),   8)
#define Request_CALLBACK NULL
#define Request_DEFAULT NULL
#define Request_Command_quit_MSGTYPE Request_Quit
#define Request_Command_run_MSGTYPE Request_RunProcess
#define Request_Command_kill_MSGTYPE Request_KillProcess
#define Request_Command_mount_9p_MSGTYPE Request_Mount9P
#define Request_Command_query_output_MSGTYPE Request_QueryOutput
#define Request_Command_put_input_MSGTYPE Request_PutInput
#define Request_Command_upload_file_MSGTYPE Request_UploadFile

#define Request_Quit_FIELDLIST(X, a) \

#define Request_Quit_CALLBACK NULL
#define Request_Quit_DEFAULT NULL

#define Request_RunProcess_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    bin,               1) \
X(a, CALLBACK, REPEATED, BYTES,    arg,               2) \
X(a, CALLBACK, REPEATED, BYTES,    env,               3) \
X(a, STATIC,   OPTIONAL, UINT32,   uid,               4) \
X(a, STATIC,   OPTIONAL, UINT32,   gid,               5) \
X(a, CALLBACK, REPEATED, MESSAGE,  redirect_fd,       6)
#define Request_RunProcess_CALLBACK pb_default_field_callback
#define Request_RunProcess_DEFAULT NULL
#define Request_RunProcess_redirect_fd_MSGTYPE RedirectFd

#define Request_KillProcess_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   process_id,        1)
#define Request_KillProcess_CALLBACK NULL
#define Request_KillProcess_DEFAULT NULL

#define Request_Mount9P_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   vol_tag,           1) \
X(a, CALLBACK, REQUIRED, BYTES,    path,              2)
#define Request_Mount9P_CALLBACK pb_default_field_callback
#define Request_Mount9P_DEFAULT NULL

#define Request_QueryOutput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   process_id,        1) \
X(a, STATIC,   OPTIONAL, UINT64,   offset,            2) \
X(a, STATIC,   OPTIONAL, UINT64,   len,               3)
#define Request_QueryOutput_CALLBACK NULL
#define Request_QueryOutput_DEFAULT NULL

#define Request_PutInput_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT64,   process_id,        1) \
X(a, STATIC,   REQUIRED, UINT32,   fd,                2) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              3)
#define Request_PutInput_CALLBACK pb_default_field_callback
#define Request_PutInput_DEFAULT NULL

#define Request_UploadFile_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, BYTES,    file_path,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   file_erm,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   uid,               3) \
X(a, STATIC,   OPTIONAL, UINT32,   guid,              4) \
X(a, CALLBACK, REQUIRED, BYTES,    data,              5)
#define Request_UploadFile_CALLBACK pb_default_field_callback
#define Request_UploadFile_DEFAULT NULL

#define RedirectFd_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   fd,                1) \
X(a, CALLBACK, ONEOF,    STRING,   (Type,output_file,Type.output_file),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (Type,pipe_blocking,Type.pipe_blocking),   3) \
X(a, STATIC,   ONEOF,    UINT32,   (Type,pipe_cyclic,Type.pipe_cyclic),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (Type,input_pipe_blocking,Type.input_pipe_blocking),   5)
#define RedirectFd_CALLBACK pb_default_field_callback
#define RedirectFd_DEFAULT NULL

extern const pb_msgdesc_t Request_msg;
extern const pb_msgdesc_t Request_Quit_msg;
extern const pb_msgdesc_t Request_RunProcess_msg;
extern const pb_msgdesc_t Request_KillProcess_msg;
extern const pb_msgdesc_t Request_Mount9P_msg;
extern const pb_msgdesc_t Request_QueryOutput_msg;
extern const pb_msgdesc_t Request_PutInput_msg;
extern const pb_msgdesc_t Request_UploadFile_msg;
extern const pb_msgdesc_t RedirectFd_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Request_fields &Request_msg
#define Request_Quit_fields &Request_Quit_msg
#define Request_RunProcess_fields &Request_RunProcess_msg
#define Request_KillProcess_fields &Request_KillProcess_msg
#define Request_Mount9P_fields &Request_Mount9P_msg
#define Request_QueryOutput_fields &Request_QueryOutput_msg
#define Request_PutInput_fields &Request_PutInput_msg
#define Request_UploadFile_fields &Request_UploadFile_msg
#define RedirectFd_fields &RedirectFd_msg

/* Maximum encoded size of messages (where known) */
/* Request_size depends on runtime parameters */
#define Request_Quit_size                        0
/* Request_RunProcess_size depends on runtime parameters */
#define Request_KillProcess_size                 11
/* Request_Mount9P_size depends on runtime parameters */
#define Request_QueryOutput_size                 33
/* Request_PutInput_size depends on runtime parameters */
/* Request_UploadFile_size depends on runtime parameters */
/* RedirectFd_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
