[package]
name = "rinit"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
nix = { version = "0.29.0", features = [
  "mount",
  "fs",
  "socket",
  "signal",
  "event",
  "ioctl",
  "net",
] }
